### PR TITLE
Fixing RegEx-62

### LINKED ISSUE #62: Add RegEx (regular expression to the email and password registration )
Hi again @Mayuresh-22 I believe i can add Regular expression control to the email Input so that user can fill a correct email function 
and the same too 
gmail_reg_ex
for password to input a moderate and secure password

### PR DESCRIPTION
**Pull request by GauriGA**
The changes made to the db/validate.php file are designed to add email and password validation using regular expressions. These changes should help improve the security and accuracy of the registration and login processes by ensuring that the provided email and password adhere to specific standards.
close #62

### CODE REVIEW

**Comment by GauriGA** [comment]
Password criteria:
-At least 8 characters in length.
-At least one uppercase letter.
-At least one lowercase letter.
-At least one digit (0-9).

For eg:            ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$
        ^: Asserts the start of the string.
        (?=.*[a-z]): Positive lookahead to ensure at least one lowercase letter is present.
        (?=.*[A-Z]): Positive lookahead to ensure at least one uppercase letter is present.
        (?=.*\d): Positive lookahead to ensure at least one digit is present.
        .{8,}: Matches any character (except for a newline character) at least 8 times.

Examples of valid passwords according to this policy: StrongPass123, SecurePwd2022, AbcdEfgh123

**Review by Mayuresh-22 — APPROVED** [review]
perfect 🎉

**Comment by Mayuresh-22** [comment]
@GauriGA That is great it will surely help make the platform more secure 🤗. Congratulations on creating your first pull request! & I am merging it right away.

**Comment by GauriGA** [comment]
@Mayuresh-22 Thank you.
Can you assign me some more issues? 
And also, if I delete this fork, it won't be a problem, right?

**Comment by Mayuresh-22** [comment]
Deleting the fork will not be a problem as your changes are already merged. You can always look for open issues in the repo as this is a two-month-long event more and more issues will be added.

**Pull request merged**
