### PR TITLE
Added Confirmation Logout Pop Up 

### PR DESCRIPTION
**Pull request by Amine2000s**
solved #61 
Confiramtion_logout_on_message
confirmation_logout_on_about_us
confirmation_logout_on_feed
confirmation_logout_on_account

### CODE REVIEW

**Comment by Mayuresh-22** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/mayuresh-22/minglr) found multiple issues last seen at cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d:

#### Unexpected duplicate &quot;display&quot; (declaration-block-no-duplicate-properties)
- [ ]  [style\account.css:297](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/account.css#L297)
- [ ]  [style\feed.css:140](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/feed.css#L140)
- [ ]  [style\message.css:94](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/message.css#L94)

#### Unexpected duplicate &quot;border&quot; (declaration-block-no-duplicate-properties)
- [ ]  [style\account.css:304](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/account.css#L304)
- [ ]  [style\feed.css:147](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/feed.css#L147)
- [ ]  [style\message.css:101](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/message.css#L101)
- [ ]  [style\about.css:65](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/about.css#L65)

#### Unexpected duplicate &quot;padding&quot; (declaration-block-no-duplicate-properties)
- [ ]  [style\account.css:303](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/account.css#L303)
- [ ]  [style\feed.css:146](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/feed.css#L146)
- [ ]  [style\message.css:100](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/message.css#L100)
- [ ]  [style\about.css:64](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/about.css#L64)

#### Unexpected duplicate &quot;background-color&quot; (declaration-block-no-duplicate-properties)
- [ ]  [style\account.css:302](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/account.css#L302)
- [ ]  [style\feed.css:145](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/feed.css#L145)
- [ ]  [style\message.css:99](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/message.css#L99)
- [ ]  [style\about.css:63](https://github.com/Mayuresh-22/Minglr/blob/cc363b7543a61c52b3c42dc8c559cdbb4bd8e28d/style/about.css#L63)

**Comment by Amine2000s** [comment]
now everything is fixed

**Comment by Mayuresh-22** [comment]
Hey @ Amine2000s, you have done a great job. But I saw you removed the password requirement JS code too. That's one of the important parts as the user gets the hint about the valid password they can use on Minglr. So please add it back so that it will again be a part of Minglr codebase.

**Comment by Amine2000s** [comment]
ohh! soory i forgot to get it back i will get it back

**Comment by Amine2000s** [comment]
the js confiramtion logic is back @Mayuresh-22

**Comment by Amine2000s** [comment]
the password hints is also returned @Mayuresh-22

**Comment by Amine2000s** [comment]
Password_hint


i meant this area of code , which i thought that is was kind of like a password "hint" to help user create a password with the specified rules

**Comment by Mayuresh-22** [comment]
> Password_hint
> 
> i meant this area of code , which i thought that is was kind of like a password "hint" to help user create a password with the specified rules
Yes, you are correct. However, JS code triggers the above code block to appear.
I'll suggest you to create new branch from Minglr's repo and then migrate your confirmation popup changes to it.

**Comment by Amine2000s** [comment]
@Mayuresh-22  i don't understand  , you mean to fork a new repo , or do you mean create a new branch from my own actual fork? Otherwise, otherwise i can't create a new branch from the official Minglr repo

**Comment by Amine2000s** [comment]
@Mayuresh-22 hello ?

**Comment by Mayuresh-22** [comment]
New PR with same title at #103

**Pull request closed without merging**
