### PR TITLE
Changes done for issue: #100

### LINKED ISSUE #100: [BUG] Making autocomplete off for privacy concerns
There is autocomplete by default on the form section, whenever the user clicks over it, they can see the stored cookies data. It breaches privacy and hence needs to be kept off.

screenshot:
WhatsApp Image 2024-01-24 at 17 42 49_e8c1230f

WhatsApp Image 2024-01-24 at 17 31 47_a3065ce7
 
 
 Raising a PR...kindly review the same

### PR DESCRIPTION
**Pull request by maitri-vv**
close #100 
I have made autocomplete off.
image

image

### CODE REVIEW

**Comment by maitri-vv** [comment]
Please mark it for SWOC label

**Comment by Mayuresh-22** [comment]
I am quickly checking it.

**Review by Mayuresh-22 — APPROVED** [review]
seems good to me

**Comment by Mayuresh-22** [comment]
@maitri-vv Congratulations on creating your first pull request! I am merging this PR.

**Pull request merged**
