### PR TITLE
Added Max and Min Width of Text Area 

### LINKED ISSUE #51: Limit the Maximum and Minimum Width of Text Area while Writing a post
Could you please assign me this issue under #SWOC24 @Mayuresh-22

css_issue
issue

### PR DESCRIPTION
**Pull request by Amine2000s**
Hi @Mayuresh-22  i Added the necessary CSS Attributes , Please Accept my Pr and Close #51

### CODE REVIEW

**Comment by Mayuresh-22** [comment]
@Amine2000s I see you've fixed the size issue of the text area on the account page. It would be great if you do that to the text area on the **feed page**.

**Comment by Amine2000s** [comment]
yes my pull request fixed them both on the feed and account page thats why there is chnages on 2 css files

**Review by Mayuresh-22 — APPROVED** [review]
Great ✨

**Comment by Mayuresh-22** [comment]
Merging this PR. Congratulations on creating your first pull request! 🤗

**Pull request merged**
