### PR TITLE
Fixed photos section BUG

### PR DESCRIPTION
**Pull request by raghav1482**
Bug Fix :  Issue #48 

Photos not visible in photos section of the account.

### CODE REVIEW

**Comment by raghav1482** [comment]
@Mayuresh-22  Kindly review my PR #76

**Comment by raghav1482** [comment]
@Mayuresh-22  Kindly review my PR #76 .  I have fixed the photos section BUG

**Review by Mayuresh-22 — APPROVED** [review]
Every thing looks correct to me

**Comment by Mayuresh-22** [comment]
@raghav1482 great job and I am merging this PR into Minglr

**Pull request merged**
