### PR TITLE
Dark Mode Added in Minglr

### PR DESCRIPTION
**Pull request by bhatiaarpit**
In Minglr, I've implemented dark mode across all pages and improved the user interface. 

**Here are the changes:**

1. Dark mode toggle buttons have been integrated into every page of Minglr.
2. Dark-mode CSS files have been included in the Style folder.
3. JavaScript functionality for toggling between light and dark modes has been added to the script.js file.
4. The logo of Minglr has been updated, and its associated files and images have been added to the logo folder.

**The Changes in files -** 

https://github.com/Mayuresh-22/Minglr/assets/118626392/b7b600ed-93c6-4f1a-ba7d-6ac922003599

**And the output preview -**
https://drive.google.com/file/d/1pXc4m5QQ8gp1MM3aW1hdq2Xz_uxG7-EG/view?usp=drive_link

**I've contributed these enhancements under SWOC24.**

### CODE REVIEW

**Comment by Mayuresh-22** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/mayuresh-22/minglr) found multiple issues last seen at 0fb1fe06d2bc35c6a9ce9d3c14a6045c8f18b68e:

#### Unexpected duplicate selector &quot;a&quot;, first used at line 27 (no-duplicate-selectors)
- [ ]  [style\darktheme_css\dark_style.css:417](https://github.com/Mayuresh-22/Minglr/blob/0fb1fe06d2bc35c6a9ce9d3c14a6045c8f18b68e/style/darktheme_css/dark_style.css#L417)

#### Unexpected duplicate &quot;border&quot; (declaration-block-no-duplicate-properties)
- [ ]  [style\darktheme_css\dark_account.css:158](https://github.com/Mayuresh-22/Minglr/blob/0fb1fe06d2bc35c6a9ce9d3c14a6045c8f18b68e/style/darktheme_css/dark_account.css#L158)
- [ ]  [style\lighttheme_css\light_account.css:151](https://github.com/Mayuresh-22/Minglr/blob/0fb1fe06d2bc35c6a9ce9d3c14a6045c8f18b68e/style/lighttheme_css/light_account.css#L151)
- [ ]  [style\lighttheme_css\light_feed.css:49](https://github.com/Mayuresh-22/Minglr/blob/0fb1fe06d2bc35c6a9ce9d3c14a6045c8f18b68e/style/lighttheme_css/light_feed.css#L49)

**Comment by bhatiaarpit** [comment]
@Mayuresh-22 I fixed the issues caused by having duplicate "a" selectors and redundant "border" declarations.

**Comment by Mayuresh-22** [comment]
Okay I'll check further

**Comment by Mayuresh-22** [comment]
Congratulations! Your PR is merged successfully and thank you so much for creating a valuable contributions to Minglr

**Pull request merged**
