### PR TITLE
Added delete button functionality  on the page for to delete the post from both frontend and backend please merge 

### PR DESCRIPTION
**Pull request by Ankita-0302**

### CODE REVIEW

**Comment by Ankita-0302** [comment]
#112

**Comment by Ankita-0302** [comment]
please check and revert back

**Comment by Mayuresh-22** [comment]
You have removed dozens of useful codes from the files, affecting the front end's UX. Just implementing the Delete (icon will be preferred) function, which should not require removing useful code.

**Comment by Ankita-0302** [comment]
I have made some changes, please check

**Comment by Mayuresh-22** [comment]
Okay I'll check

**Comment by Mayuresh-22** [comment]
## (On account.php after the user is logged in)
### The image posts and the footer are not visible 
image

### Changes are not responsive on mobile devices
image

**Comment by Mayuresh-22** [comment]
@Ankita-0302 any update?

**Pull request closed without merging**
