### PR TITLE
New search UI Has been Added with new Search Logic

### PR DESCRIPTION
**Pull request by Jenis07**
in this i have solved the issue #13 with the requirements..

### CODE REVIEW

**Review by Mayuresh-22 — CHANGES_REQUESTED** [review]
UI is great, but there is a small bug when we try to visit the account page of any user i.e it shows the UI of search results (recently you implemented).

## What is expected?
If a user searches "Jhon" all the users with username/name Jhon should be visible in the search list UI. But when they click on any of the profiles they should be redirected to their profile.

## What to do?
1.  As you get the username through the "username" GET parameter in the URL. You can add a separate parameter called "search" so whenever the user searches, the URL will look like this "http://localhost/Minglr/account.php?search=jhon123" (You can do this by changing the action in the "back/search.php" file) and you can use the search UI here to show the result.
2.  Now if the user clicks any profile they should be reacted to their profile. Now the URL should look like this "http://localhost/Minglr/account.php?username=jhon123" and they will see all the posts and other things of the user.

This will keep account and search logic separate currently what happening is whenever I am visiting the profile of any user it shows the same Search UI instead of the Account Page.

If you have any doubts feel free to ping here.

**Comment by Jenis07** [comment]
I have changes implemented i am uploading the video of the newly implemented changes.
[new changes.zip](https://github.com/Mayuresh-22/Minglr/files/13212629/new.changes.zip)

**Comment by Mayuresh-22** [comment]
Great @Jenis07, watched the video demo and now its working perfect 👍

**Comment by Jenis07** [comment]
I have commited the new changes

**Review by Mayuresh-22 — APPROVED** [review]
Seems good now

**Comment by Mayuresh-22** [comment]
Merging this PR

**Pull request merged**
