### PR TITLE
Chore : Update README.md ✅

### PR DESCRIPTION
**Pull request by YashkShrivas4491**
Chore: Update README.md ✅ #89

### CODE REVIEW

**Review by Mayuresh-22 — APPROVED** [review]
good

**Comment by Mayuresh-22** [comment]
Have you made required changes?

**Comment by Mayuresh-22** [comment]
Change this link to Minglr's GitHub repository link
`<a href="https://github.com/YashkShrivas4491/Machine_Coding_Projects-/contributors">`

**Comment by YashkShrivas4491** [comment]
> Change this link to Minglr's GitHub repository link `<a href="https://github.com/YashkShrivas4491/Machine_Coding_Projects-/contributors">`

ok

**Comment by YashkShrivas4491** [comment]
> Change this link to Minglr's GitHub repository link `<a href="https://github.com/YashkShrivas4491/Machine_Coding_Projects-/contributors">`

Done ✅

**Review by Mayuresh-22 — APPROVED** [review]
seems good

**Review by Mayuresh-22 — APPROVED** [review]

**Pull request merged**
