### PR TITLE
Send-message button made responsive

### PR DESCRIPTION
**Pull request by pankhuri92**
I have ensured the responsiveness of the button in all the three versions of mobile view via media query.

### CODE REVIEW

**Comment by Mayuresh-22** [comment]
**You have done great work fixing the CSS but there is a bug in it. If the username is big the button still comes down.**



# What you can do?
Try creating two buttons, keep the current button for the desktop and the second button right below the username/name.
The desktop button will not be visible on mobile devices and vice versa.

### Desktop


### Mobile

(its a representation)

**Comment by pankhuri92** [comment]
Will make sure of that and then create pr again.

**Comment by pankhuri92** [comment]
So I have done as per asked. I created two buttons, keeping the original visible only in desktop version. While the other, column aligned with name & username. It will appear only in mobile versions.
Screenshot 2024-01-01 213042
Screenshot 2024-01-01 213100
Screenshot 2024-01-01 213116
Screenshot 2024-01-01 213133

**Review by Mayuresh-22 — APPROVED** [review]
Changes are as expected

**Comment by Mayuresh-22** [comment]
Hey @pankhuri92, You did a great job. Everything seems good and I'll merge it.

**Comment by pankhuri92** [comment]
Thanks @Mayuresh-22 !

**Pull request merged**
