### PR TITLE
Added New Footer Style [fixes #33]

### LINKED ISSUE #33: [feat] Change footer style
# What is expected?
Kindly modify the style of the footer to enhance its visual appeal. Your attention to this matter is greatly appreciated.

### PR DESCRIPTION
**Pull request by Ab369**
- Added new Footer Style
- Used HTML, CSS and JavaScript
- Added Social media links
- Added new Footer Navbar
- Added Arrow which takes to top of page

### CODE REVIEW

**Comment by Mayuresh-22** [comment]
## An issue with the PR

### Home page:
image

### Account and other pages
image

**Comment by Ab369** [comment]
I have updated index.php
Please review it

**Comment by Ab369** [comment]
I will work on this

**Comment by Ab369** [comment]
Please review the changes

**Comment by Ab369** [comment]
I have made the changes.
Please review it

**Comment by Mayuresh-22** [comment]
Current changes seem good I would like to suggest a few things:

1. Reduce spaces between social icons.
2. Add space between footer and page content to prevent content from getting hidden in the top navbar. (Highlighted in the image below)
Capture
(Content is shrinking in between the navbar top limit and the footer.
3. Make the design responsive current changes are not responsive on mobile devices and other devices.

**Comment by Ab369** [comment]
Sure, I will work on this

**Comment by Ab369** [comment]
hey, I have updated the CSS with responsiveness.
Please check it.

**Comment by Mayuresh-22** [comment]
There's still no enough space at the top of the page.
image

**Comment by Ab369** [comment]
Hey @Mayuresh-22 , I am unable to figure out further and unable to work on this issue due to some other project.
Please unassign this issue from me.
Thanks for your consideration.

**Pull request closed without merging**
