### PR TITLE
Feat: enhanced homepage

### LINKED ISSUE #65: Feat: Enhance the homepage
I'd love to enhance the homepage for reference these are  my other works
c3312a9c-9807-46a2-a2b2-5bf0cc407556
fc8f37e9-30a0-4704-a831-c465acda6e3d

### PR DESCRIPTION
**Pull request by Yatin12527**
Fixed #65 
Hey as promised I tried to improve the overall look of homepage by incorporating images and trying new style to design the display.
I tried to stay faithful to the blue and white color theme as much as it was possible with the current design.
I left the buttons hover effects as it is as I only asked for changing design patter but I'm more than happy to add or subtract from this design as you might like.
Here's before vs after comparison:-

**Before**
image

**After**

https://github.com/Mayuresh-22/Minglr/assets/134225415/f8991fd2-5c3f-4677-a499-e8aa242ff964

Also the lag in recording is some glitch in my system I don't know why it does that.

### CODE REVIEW

**Comment by Mayuresh-22** [comment]
That's looking awesome @Yatin12527 🤗. I am merging this PR. Congratulations on creating your first pull request!

**Comment by Yatin12527** [comment]
> That's looking awesome @Yatin12527 🤗. Congratulations on creating your first pull request! I tested it on my machine and found the design is not responsive. Have look into it.

Hey mayuresh im

**Comment by 1-ankush-1** [comment]
> > That's looking awesome @Yatin12527 🤗. Congratulations on creating your first pull request! I tested it on my machine and found the design is not responsive. Have look into it.
> 
> Hey mayuresh I'm glad u liked the design but I'm not rly good at creating responsive designs i might end up making it worse so if u still wanna give the issue to me then i can try but it'd be better if someone who knows it better does it :)


## Approch to solve - @Yatin12527  try this approch
 - use media queries . on smaller screen hide the left side which is image ex- just give that image a classname and make add display none on small screen.

Hey @Mayuresh-22 if @Yatin12527 will not be able to solve it i will be happy to take this issue.

**Comment by Yatin12527** [comment]
> > > That's looking awesome @Yatin12527 🤗. Congratulations on creating your first pull request! I tested it on my machine and found the design is not responsive. Have look into it.
> > 
> > 
> > Hey mayuresh I'm glad u liked the design but I'm not rly good at creating responsive designs i might end up making it worse so if u still wanna give the issue to me then i can try but it'd be better if someone who knows it better does it :)
> 
> ## Approch to solve - @Yatin12527 try this approch
> * use media queries . on smaller screen hide the left side which is image ex- just give that image a classname and make add display none on small screen.
> 
> Hey @Mayuresh-22 if @Yatin12527 will not be able to solve it i will be happy to take this issue.
Ik how the issue might be fixed using media queries but i've not worked enough on responsive designs to take on this work is all i'm saying and i'll be happy to share the issue with u :)

**Comment by Mayuresh-22** [comment]
Okay then, do you want to continue working on this issue @1-ankush-1?

**Comment by 1-ankush-1** [comment]
> Okay then, do you want to continue working on this issue @1-ankush-1?
 
I can make it responsive.
you can assign this to me.

**Comment by Mayuresh-22** [comment]
@1-ankush-1 I am assigning it to you...

**Pull request closed without merging**
